# Generated by Django 2.0.6 on 2018-06-16 04:24

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180609_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('location', location_field.models.spatial.LocationField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='local_is_uni',
            field=models.BooleanField(default=False),
        ),
    ]
