# Generated by Django 2.0.6 on 2018-06-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180627_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueIdentifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
