# Generated by Django 2.0.6 on 2018-06-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_uniqueidentifiers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='local_is_uni',
            new_name='locale_is_uni',
        ),
    ]
