# Generated by Django 2.0.6 on 2018-06-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180629_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
